export enum AuditAction {
  CREATE_ORGANIZATION = 'CREATE_ORGANIZATION',

  CREATE_PROJECT = 'CREATE_PROJECT',

  CREATE_FEATURE_FLAG = 'CREATE_FEATURE_FLAG',

  TOGGLE_FEATURE_FLAG = 'TOGGLE_FEATURE_FLAG',

  UPDATE_ROLLOUT = 'UPDATE_ROLLOUT',
}