export enum AuditAction {
  CREATE_ORGANIZATION = 'CREATE_ORGANIZATION',

  CREATE_PROJECT = 'CREATE_PROJECT',

  CREATE_FEATURE_FLAG = 'CREATE_FEATURE_FLAG',

  TOGGLE_FEATURE_FLAG = 'TOGGLE_FEATURE_FLAG',

  UPDATE_ROLLOUT = 'UPDATE_ROLLOUT',
  SEND_ORGANIZATION_INVITATION = 'SEND_ORGANIZATION_INVITATION',

ACCEPT_ORGANIZATION_INVITATION = 'ACCEPT_ORGANIZATION_INVITATION',

REJECT_ORGANIZATION_INVITATION = 'REJECT_ORGANIZATION_INVITATION',

CANCEL_ORGANIZATION_INVITATION = 'CANCEL_ORGANIZATION_INVITATION',
ADD_PROJECT_MEMBER = 'ADD_PROJECT_MEMBER',

REMOVE_PROJECT_MEMBER = 'REMOVE_PROJECT_MEMBER',

UPDATE_PROJECT_MEMBER_ROLE = 'UPDATE_PROJECT_MEMBER_ROLE',
}